### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by KomalChugh** [sid230798/G6_SE_Business_Workflow#3]
add a profile page where users can fill in their department information and can also change their password.

**Comment by Singh-Rishabh** [comment]
Added the profile page (user can add their name and department)
The password change part is yet to be done. Will do it in next commit
(see changes here - https://github.com/sid230798/G6_SE_Business_Workflow/commit/bfe62423dd390c31b5b92f04d64d8d8047356b18)

**Comment by Singh-Rishabh** [comment]
Added password change option for users. 
(see changes here - https://github.com/sid230798/G6_SE_Business_Workflow/commit/0ce6e2320510df0385cd58851d2e867cba025edd)
